/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;

import javax.swing.*;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import java.io.IOException;
/**
 *
 * @author Kumar
 */
public class barcode_generator extends javax.swing.JFrame {

    /**
     * Creates new form barcode_generator
     */
    public barcode_generator() {
        initComponents();
    }
    
    private BufferedImage createBarCode(String txt, int height, int width) throws Exception{
         BitMatrix bitMatrix = new MultiFormatWriter().encode(txt, BarcodeFormat.CODE_128, width, height);
         return MatrixToImageWriter.toBufferedImage(bitMatrix);
    }
    
    private BufferedImage barcodeImage;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_label = new javax.swing.JLabel();
        text = new javax.swing.JTextField();
        barcode_image = new javax.swing.JLabel();
        generateBarcode = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BARCODE GENERATOR PAGE");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_label.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        text_label.setText("ENTER THE TEXT");
        getContentPane().add(text_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 130, -1, -1));

        text.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 130, 177, -1));

        barcode_image.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(barcode_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 300, 100));

        generateBarcode.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        generateBarcode.setText("GENERATE");
        generateBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBarcodeActionPerformed(evt);
            }
        });
        getContentPane().add(generateBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 386, -1, -1));

        reset.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 386, -1, -1));

        close.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 386, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("BARCODE GENERATOR PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 24, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/otp_back.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
         this.dispose();
          new barcode_generator().setVisible(true);
        
    }//GEN-LAST:event_resetActionPerformed

    private void generateBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBarcodeActionPerformed
        // TODO add your handling code here:
        String text1 = text.getText();
        if (text1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter the text !!!");
        }
        try{
            barcodeImage = createBarCode(text1,100,300);
            barcode_image.setIcon(new ImageIcon(barcodeImage));
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
        if(barcode_image != null){
            JFileChooser jf = new JFileChooser();
            int result = jf.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION){
                File file = jf.getSelectedFile();
                try{
                   ImageIO.write(barcodeImage, "png", file);
                   JOptionPane.showMessageDialog(this, "File Saved Sucessfully !!!");
                } 
                catch (IOException e){
                    JOptionPane.showMessageDialog(this, e);
                }
            }
        }
             
    }//GEN-LAST:event_generateBarcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barcode_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barcode_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barcode_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barcode_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barcode_generator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barcode_image;
    private javax.swing.JButton close;
    private javax.swing.JButton generateBarcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton reset;
    private javax.swing.JTextField text;
    private javax.swing.JLabel text_label;
    // End of variables declaration//GEN-END:variables
}
