/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;

import java.io.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Kumar
 */
public class buyers_add extends javax.swing.JFrame {

    /**
     * Creates new form buyers_add
     */
    public buyers_add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        addbuyer = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buyer_add.jpeg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BUYERS ADD PAGE");
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-user.png"))); // NOI18N
        jLabel1.setText("BUYERS ADD PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 303, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setText("NAME");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 150, 77, -1));

        name.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 147, 134, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setText("NUMBER");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 193, 77, 22));

        number.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 191, 134, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel9.setText("GENDER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 238, 67, -1));

        gender.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHERS" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 235, 134, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel10.setText("EMAIL");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 282, 77, -1));

        email.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 279, 134, -1));

        addbuyer.setBackground(new java.awt.Color(204, 204, 204));
        addbuyer.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        addbuyer.setText("ADD");
        addbuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuyerActionPerformed(evt);
            }
        });
        getContentPane().add(addbuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 386, -1, -1));

        reset.setBackground(new java.awt.Color(255, 255, 153));
        reset.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 386, -1, -1));

        close.setBackground(new java.awt.Color(255, 51, 51));
        close.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 92, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill_background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean isNumberExist(String num){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=jmdb;TrustServerCertificate=True;user=arun;password=Ineedmoney5!");
            PreparedStatement pst = con.prepareStatement("select count(*) from tbl_buyer where Number = ?");
            pst.setString(1, num);
            ResultSet rs = pst.executeQuery();
            if (rs.next()){
                return rs.getInt(1) > 0;
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        return false;
    }
    private void addbuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuyerActionPerformed
        // TODO add your handling code here:
        String name1 = name.getText();
        String num = number.getText();
        String email1 = email.getText();
        String gender1 = (String) gender.getSelectedItem();

        if (!name1.isEmpty() && !num.isEmpty() && !email1.isEmpty() && !gender1.isEmpty()) {
            if (!isNumberExist(num)) {
                JFileChooser filechooser;
                filechooser = new JFileChooser();
                int result = filechooser.showOpenDialog(this);
                if (result == JFileChooser.APPROVE_OPTION) {
                    try {
                        File selectedFile = filechooser.getSelectedFile();
                        FileInputStream fis = new FileInputStream(selectedFile);
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                        Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=jmdb;TrustServerCertificate=True;user=arun;password=Ineedmoney5!");
                        PreparedStatement pst = con.prepareStatement("sp_buyer_insert ?,?,?,?,?");
                        pst.setString(1, name1);
                        pst.setString(2, num);
                        pst.setString(3, gender1);
                        pst.setString(4, email1);
                        pst.setBinaryStream(5, fis,(int) selectedFile.length());
                        int i = pst.executeUpdate();
                        if (i != 0){
                            JOptionPane.showMessageDialog(this, "Buyer Added Sucessfully!!");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e);
                    }
                }else{
                     JOptionPane.showMessageDialog(this, "Upload the image!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Same number exist!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter all the datas");
        }
    }//GEN-LAST:event_addbuyerActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new buyers_add().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buyers_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buyers_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buyers_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buyers_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buyers_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbuyer;
    private javax.swing.JButton close;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
