/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.*;
import java.io.BufferedInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileWriter;
/**
 *
 * @author Kumar
 */
public class buyers_details extends javax.swing.JFrame {

    /**
     * Creates new form buyers_details
     */
    private DefaultTableModel m;
    private final JTable Table1;
    
    private class ImageRenderer extends JLabel implements TableCellRenderer{
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,boolean isSelected,
                boolean hasFocus, int row, int column){
            if (value instanceof ImageIcon){
                setIcon((ImageIcon)value);
            } else{
                setText("No image");
            }
            return this;
        }
    }
    public buyers_details() {
        initComponents();
        String[] columns = {"NAME", "IMAGE", "NUMBER", "GENDER", "EMAIL"};
        m = new DefaultTableModel(columns, 0);
        Table1 = new JTable(m) {
            @Override
            public TableCellRenderer getCellRenderer(int row, int col) {
                if (col == 1) {
                    return new ImageRenderer();
                }
                return super.getCellRenderer(row, col);
            }
        };
        
        this.setLayout(new BorderLayout());
        this.add(new JScrollPane(Table1), BorderLayout.CENTER);
        this.setSize(400,400);
        Table1.setRowHeight(80);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        details = new javax.swing.JButton();
        print = new javax.swing.JButton();
        close = new javax.swing.JButton();
        csv_file = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BUYERS_DETAILS_PAGE");
        setMinimumSize(new java.awt.Dimension(727, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        details.setBackground(new java.awt.Color(255, 153, 204));
        details.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        details.setText("DETAILS");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });
        getContentPane().add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        print.setBackground(new java.awt.Color(102, 204, 255));
        print.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, -1, -1));

        close.setBackground(new java.awt.Color(255, 51, 51));
        close.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, -1, -1));

        csv_file.setBackground(new java.awt.Color(255, 255, 153));
        csv_file.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        csv_file.setText("CSV FILE");
        csv_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csv_fileActionPerformed(evt);
            }
        });
        getContentPane().add(csv_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
        // TODO add your handling code here:
        try{
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=jmdb;TrustServerCertificate=True;user=arun;password=Ineedmoney5!");
        PreparedStatement pst = con.prepareStatement("sp_buyer_get");
        ResultSet rs = pst.executeQuery();
        while (rs.next()){
            String name1 = rs.getString("Name");
            String num = rs.getString("Number");
            String gender = rs.getString("Gender");
            String email = rs.getString("Email");
            byte[] imgBytes = rs.getBytes("Img");
            
            ImageIcon imageicon = null;
            if (imgBytes != null){
                InputStream is = new ByteArrayInputStream(imgBytes);
                BufferedImage bufferedimage = ImageIO.read(is);
                imageicon = new ImageIcon(bufferedimage);
            }
            m.addRow(new Object[]{name1,imageicon,num,gender,email});
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_detailsActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try{
            Table1.print(JTable.PrintMode.NORMAL);
            JOptionPane.showMessageDialog(this, "PDF Saved Sucessfully!!!");
        } catch(Exception e){
             JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_printActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void csv_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csv_fileActionPerformed
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser();
        int result = jf.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jf.getSelectedFile();
            String path = file.getAbsolutePath();
            if (!path.endsWith(".csv")) {
                path += ".csv";
            }
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(path))) {
                for (int i = 0; i < Table1.getColumnCount(); i++) {
                    writer.write(Table1.getColumnName(i));
                    if (i < Table1.getColumnCount() - 1) {
                        writer.write(",");
                    }

                }
                writer.newLine();
                for (int i = 0; i < Table1.getRowCount(); i++) {
                    for (int j = 0; j < Table1.getColumnCount(); j++) {
                        writer.write(Table1.getValueAt(i, j).toString());
                        if (i < Table1.getColumnCount() - 1) {
                            writer.write(",");
                        }
                    }
                    writer.newLine();
                }
                JOptionPane.showMessageDialog(this, "File Exported Sucessfully!!!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_csv_fileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buyers_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buyers_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buyers_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buyers_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buyers_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton csv_file;
    private javax.swing.JButton details;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
