/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;
import javax.mail.*;
import javax.mail.internet.*;
//import javax.activation.*;
import java.io.File;
import javax.swing.*;
//import javax.swing.JFileChooser;
//import javax.swing.JOptionPane;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import java.util.Properties;
import javax.sql.*;
/**
 *
 * @author Kumar
 */
public class email_page extends javax.swing.JFrame {

    /**
     * Creates new form email_page
     */
    private File SelectedFile;
    public email_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        senderEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        subject = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        receiverEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        attach = new javax.swing.JButton();
        send = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel6.setText("jLabel2");

        jLabel7.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMAIL PAGE");
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("EMAIL PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 19, 146, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("SENDER EMAIL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 92, -1, 22));

        senderEmail.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(senderEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 90, 154, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 151, 88, 22));

        password.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 149, 154, -1));

        subject.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 264, 154, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setText("RECEIVER EMAIL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 205, -1, 22));

        receiverEmail.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(receiverEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 203, 154, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setText("SUBJECT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 266, 88, 22));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setText("MESSAGE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 321, 88, 22));

        message.setColumns(20);
        message.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        message.setLineWrap(true);
        message.setRows(5);
        message.setWrapStyleWord(true);
        jScrollPane1.setViewportView(message);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 321, 154, 70));

        attach.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        attach.setText("ATTACH");
        attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachActionPerformed(evt);
            }
        });
        getContentPane().add(attach, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 243, -1, -1));

        send.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        send.setText("SEND");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        getContentPane().add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 314, -1, -1));

        reset.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        close.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product_delete_background.jpeg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
        String fromEmail = senderEmail.getText();
        String pass = password.getText();
        String toEmail = receiverEmail.getText();
        String sub = subject.getText();
        String msg = message.getText();

        String email1 = receiverEmail.getText();
        String regex = "^[a-zA-Z0-9]+(?:\\.[a-zA-Z0-9]+)*@(?:[a-z]+\\.)+[a-z]{2,3}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(email1);

        if (matcher.matches()){
            JOptionPane.showMessageDialog(this,"Email matched Sucessfully");
        }
        else{
             JOptionPane.showMessageDialog(this,"Email doesn't matched");
        }
        
        if (SelectedFile == null ){
            JOptionPane.showMessageDialog(this,"Choose a file to attach");
        }
        
        Properties prop = new Properties();
        prop.put("mail.smtp.host","smtp.gmail.com");
        prop.put("mail.smtp.port", "587");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true");
        
        Session session = Session.getInstance(prop,new javax.mail.Authenticator(){
            @Override
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(fromEmail,pass);
            }
        });
        
        try{
        MimeMessage mime = new MimeMessage(session);
        
        mime.setFrom(new InternetAddress(fromEmail));
        
        mime.addRecipient(Message.RecipientType.TO,new InternetAddress(toEmail));
        
        mime.setSubject(sub);
        
        BodyPart messageBodyPart = new MimeBodyPart();
        messageBodyPart.setText(msg);
        
        Multipart multipart = new MimeMultipart();
        multipart.addBodyPart(messageBodyPart);
        
        messageBodyPart = new MimeBodyPart();
//        DataSource datasource = new FileDataSource(SelectedFile);
//        messageBodyPart.setDataHandler(new DataHandler(datasource));
        messageBodyPart.setFileName(SelectedFile.getName());
        multipart.addBodyPart(messageBodyPart);
        
        mime.setContent(multipart);
        
        Transport.send(mime);
        JOptionPane.showMessageDialog(this,"Mail sent sucessfully!!!");
        }catch(MessagingException e){
            JOptionPane.showMessageDialog(this,e);
        }
        
    }//GEN-LAST:event_sendActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        this.dispose();
         new email_page().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachActionPerformed
        // TODO add your handling code here:'
        JFileChooser jfilechooser = new JFileChooser();
        int result = jfilechooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION){
            SelectedFile = jfilechooser.getSelectedFile();
            JOptionPane.showMessageDialog(this,"Selected file: "+SelectedFile.getName());
        }
        
       
        
    }//GEN-LAST:event_attachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(email_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(email_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(email_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(email_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new email_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attach;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextArea message;
    private javax.swing.JTextField password;
    private javax.swing.JTextField receiverEmail;
    private javax.swing.JButton reset;
    private javax.swing.JButton send;
    private javax.swing.JTextField senderEmail;
    private javax.swing.JTextField subject;
    // End of variables declaration//GEN-END:variables
}
