/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;
import javax.swing.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Kumar
 */
public class forget_password extends javax.swing.JFrame {

    /**
     * Creates new form forget_password
     */
    public forget_password() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        admin_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        old_password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        new_password = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        conform_password = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sqst = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sans = new javax.swing.JTextField();
        reset_password = new javax.swing.JButton();
        forgot_password = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORGOT AND RESET PASSWORD");
        setMinimumSize(new java.awt.Dimension(550, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel1.setText("FORGOT AND RESET PASSWORD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("ADMIN NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 114, -1, -1));

        admin_name.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(admin_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 111, 174, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setText("OLD PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 158, 159, -1));

        old_password.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(old_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 155, 174, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setText("NEW PASSWORD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 202, -1, -1));

        new_password.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(new_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 199, 174, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setText("CONFORM PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 246, -1, -1));

        conform_password.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(conform_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 243, 174, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel6.setText("SECURITY QUESTION");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 159, -1));

        sqst.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(sqst, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 287, 174, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setText("SECURITY ANSWER");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 334, 140, -1));

        sans.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        sans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sansKeyReleased(evt);
            }
        });
        getContentPane().add(sans, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 331, 174, -1));

        reset_password.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        reset_password.setText("RESET PASSWORD");
        reset_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(reset_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 422, -1, -1));

        forgot_password.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        forgot_password.setText("FORGOT PASSWORD");
        forgot_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgot_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(forgot_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        reset.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 491, -1, -1));

        close.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 491, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgot_pass.jpeg"))); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new forget_password().setVisible(true);
        
    }//GEN-LAST:event_resetActionPerformed

    private void forgot_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgot_passwordActionPerformed
        // TODO add your handling code here:
        try{
            String name = admin_name.getText();
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=jmdb;TrustServerCertificate=True;user=arun;password=Ineedmoney5!");
            PreparedStatement pst = con.prepareStatement("select SQuestion from tbl_admin where name = ?");
            pst.setString(1,name);
            ResultSet rs = pst.executeQuery();
            if (rs.next()){
                JOptionPane.showMessageDialog(this,"Answer the security question");
                sqst.setText(rs.getString("SQuestion"));
            }
        } catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_forgot_passwordActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void sansKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sansKeyReleased
        // TODO add your handling code here:
        try{
            String ans = sans.getText();
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=jmdb;TrustServerCertificate=True;user=arun;password=Ineedmoney5!");
            PreparedStatement pst = con.prepareStatement("select pwd from tbl_admin where SAnswer = ?");
            pst.setString(1,ans);
            ResultSet rs = pst.executeQuery();
            if (rs.next()){
                JOptionPane.showMessageDialog(this,"Old password Retrieved Sucessfully!!");
                old_password.setText(rs.getString("pwd"));
            }
        } catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_sansKeyReleased

    private void reset_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_passwordActionPerformed
        // TODO add your handling code here:
       
        try{
            String name = admin_name.getText();
            String opass = old_password.getText();
            String newpass = new_password.getText();
            String cpass = conform_password.getText();
            if (!opass.equals(newpass) && newpass.equals(cpass) && !name.isEmpty() && !opass.isEmpty() && !newpass.isEmpty() && !cpass.isEmpty()){
                
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=jmdb;TrustServerCertificate=True;user=arun;password=Ineedmoney5!");
                PreparedStatement pst = con.prepareStatement("update tbl_admin set pwd = ? where name = ?");
                pst.setString(1,newpass);
                pst.setString(2,name);
                int i = pst.executeUpdate();
                if (i != 0){
                    JOptionPane.showMessageDialog(this,"Password changed Sucessfully!!!");
                }
            }
            else if(opass.equals(newpass)){
                JOptionPane.showMessageDialog(this,"New password can't be same as old Password!!!");
            }
            else if(newpass.equals(cpass)){
                JOptionPane.showMessageDialog(this,"New password and confirm password should be same!!!");
            }
            
        } catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_reset_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forget_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admin_name;
    private javax.swing.JButton close;
    private javax.swing.JTextField conform_password;
    private javax.swing.JButton forgot_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField new_password;
    private javax.swing.JTextField old_password;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset_password;
    private javax.swing.JTextField sans;
    private javax.swing.JTextField sqst;
    // End of variables declaration//GEN-END:variables
}
