/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;
import javax.swing.*;
/**
 *
 * @author Kumar
 */
public class main_page extends javax.swing.JFrame {

    /**
     * Creates new form main_page
     */
    int z = 0;
    public main_page() {
        initComponents();
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        b5.setVisible(false);
        b6.setVisible(false);
        b7.setVisible(false);
        b8.setVisible(false);
        b9.setVisible(false);
        b10.setVisible(false);
        b11.setVisible(false);
        b12.setVisible(false);
        b13.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAIN PAGE");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow1.jpg"))); // NOI18N
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 53, 44));

        b3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update_buyer1.png"))); // NOI18N
        b3.setText(" BUYER UPDATE");
        b3.setIconTextGap(1);
        b3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b3ComponentShown(evt);
            }
        });
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 209, 207, -1));

        jLabel2.setBackground(new java.awt.Color(255, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("WELCOME TO JEO MART MAIN PAGE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 670, 55));

        b4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buyer_details.png"))); // NOI18N
        b4.setText("BUYER DETAILS");
        b4.setIconTextGap(1);
        b4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b4ComponentShown(evt);
            }
        });
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 209, 208, -1));

        b2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-user.png"))); // NOI18N
        b2.setText("BUYER ADD");
        b2.setIconTextGap(1);
        b2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b2ComponentShown(evt);
            }
        });
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 209, 184, 55));

        b5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_buyer.png"))); // NOI18N
        b5.setText("BUYER DELETE");
        b5.setIconTextGap(3);
        b5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b5ComponentShown(evt);
            }
        });
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 209, 208, -1));

        b9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_product.png"))); // NOI18N
        b9.setText("PRODUCT DELETE");
        b9.setToolTipText("");
        b9.setIconTextGap(1);
        b9.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b9ComponentShown(evt);
            }
        });
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 297, 208, -1));

        b7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update_product.png"))); // NOI18N
        b7.setText("PRODUCT UPDATE");
        b7.setIconTextGap(1);
        b7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b7ComponentShown(evt);
            }
        });
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 297, -1, -1));

        b6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_product.png"))); // NOI18N
        b6.setText("PRODUCT ADD");
        b6.setIconTextGap(1);
        b6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b6ComponentShown(evt);
            }
        });
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 297, -1, -1));

        b8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product_details.png"))); // NOI18N
        b8.setText("PRODUCT DETAILS");
        b8.setIconTextGap(1);
        b8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b8ComponentShown(evt);
            }
        });
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 297, -1, -1));

        b12.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        b12.setText("LOGOUT");
        b12.setToolTipText("");
        b12.setIconTextGap(1);
        b12.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b12ComponentShown(evt);
            }
        });
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 397, 208, -1));

        b11.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/utilities.jpeg"))); // NOI18N
        b11.setText("UTILITIES");
        b11.setIconTextGap(1);
        b11.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b11ComponentShown(evt);
            }
        });
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 397, 207, -1));

        b10.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billing.png"))); // NOI18N
        b10.setText("BILLING");
        b10.setIconTextGap(1);
        b10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b10ComponentShown(evt);
            }
        });
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 397, 184, -1));

        b13.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        b13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        b13.setText("EXIT");
        b13.setToolTipText("");
        b13.setIconTextGap(1);
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        getContentPane().add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 397, 133, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main_page.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        
        new buyer_update().setVisible(true);
    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:\
        new buyers_add().setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
         new buyers_details().setVisible(true);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
         new buyers_delete().setVisible(true);
    }//GEN-LAST:event_b5ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        new product_delete().setVisible(true);
    }//GEN-LAST:event_b9ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
         new product_update().setVisible(true);
        
    }//GEN-LAST:event_b7ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        new products_add().setVisible(true);
    }//GEN-LAST:event_b6ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        new product_details().setVisible(true);
    }//GEN-LAST:event_b8ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this,"DO YOU WANT TO LOGOUT ?","LOGOUT PAGE",JOptionPane.YES_NO_OPTION);
        if (a == 0){
            this.dispose();
            new admin_login().setVisible(true);
        }
    }//GEN-LAST:event_b12ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        new utilities_page().setVisible(true);
    }//GEN-LAST:event_b11ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        new billing_page().setVisible(true);
    }//GEN-LAST:event_b10ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this,"DO YOU WANT TO EXIT ?","EXIT PAGE",JOptionPane.YES_NO_OPTION);
        if (a == 0){
            System.exit(a);
        }
    }//GEN-LAST:event_b13ActionPerformed

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(250);
                b2.setVisible(true);
                
            } catch (Exception e){ }
        }
        else{
            b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        b5.setVisible(false);
        b6.setVisible(false);
        b7.setVisible(false);
        b8.setVisible(false);
        b9.setVisible(false);
        b10.setVisible(false);
        b11.setVisible(false);
        b12.setVisible(false);
        b13.setVisible(false);
        z = 0;
        }
    }//GEN-LAST:event_b1MouseClicked

    private void b3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b3ComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(250);
                b4.setVisible(true);
                
            } catch (Exception e){}
        }
    }//GEN-LAST:event_b3ComponentShown

    private void b4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b4ComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(250);
                b5.setVisible(true);
                
            } catch (Exception e){}
        }
    }//GEN-LAST:event_b4ComponentShown

    private void b5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b5ComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(250);
                b6.setVisible(true);
                
            } catch (Exception e){}
        }
        
    }//GEN-LAST:event_b5ComponentShown

    private void b6ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b6ComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(250);
                b7.setVisible(true);
                
            } catch (Exception e){}
        }
    }//GEN-LAST:event_b6ComponentShown

    private void b7ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b7ComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(250);
                b8.setVisible(true);
                
            } catch (Exception e){}
        }
    }//GEN-LAST:event_b7ComponentShown

    private void b8ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b8ComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(250);
                b9.setVisible(true);
                
            } catch (Exception e){}
        }
    }//GEN-LAST:event_b8ComponentShown

    private void b9ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b9ComponentShown
        // TODO add your handling code here:
        if(z == 0){
            try{
                Thread.sleep(250);
                b10.setVisible(true);
                
            } catch (Exception e){}
        }
    }//GEN-LAST:event_b9ComponentShown

    private void b10ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b10ComponentShown
        // TODO add your handling code here:
         if(z == 0){
            try{
                Thread.sleep(250);
                b11.setVisible(true);
                
            } catch (Exception e){}
        }
    }//GEN-LAST:event_b10ComponentShown

    private void b11ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b11ComponentShown
        // TODO add your handling code here:
         if(z == 0){
            try{
                Thread.sleep(250);
                b12.setVisible(true);
                
            } catch (Exception e){}
        }
    }//GEN-LAST:event_b11ComponentShown

    private void b12ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b12ComponentShown
        // TODO add your handling code here:
         if(z == 0){
            try{
                Thread.sleep(250);
                b13.setVisible(true);
                z = 1;
                
            } catch (Exception e){}
        }
    }//GEN-LAST:event_b12ComponentShown

    private void b2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b2ComponentShown
        // TODO add your handling code here:
         if(z == 0){
            try{
                Thread.sleep(250);
                b3.setVisible(true);
                
            } catch (Exception e){}
        }
    }//GEN-LAST:event_b2ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
