/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart_billing_system;
import java.util.Properties;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.mail.*;
import javax.mail.internet.*;
//import javax.activation;
import javax.swing.JOptionPane;
/**
 *
 * @author Kumar
 */
public class otpEmailVerification extends javax.swing.JFrame {

    /**
     * Creates new form otpEmailVerification
     */
    protected String generatedOtp;
    public otpEmailVerification() {
        initComponents();
    }
    
    protected void sendOtp(String receiverEmail, String otp){
        String fromEmail = sender.getText();
        String pass = password.getText();
        
        Properties prop = new Properties();
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", 587);
        prop.put("mail.smtp.auth","true");
        prop.put("mail.smtp.starttls.enable","true");
        
        Session session = Session.getInstance(prop, new javax.mail.Authenticator(){
            @Override
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(fromEmail,pass);
            }
        });
        
        try{
            MimeMessage mime = new MimeMessage(session);
            
            mime.setFrom(new InternetAddress(fromEmail));
            mime.setRecipient(Message.RecipientType.TO, new InternetAddress(receiverEmail));
//            mime.setRecipient(Message.RecipientType.TO, InternetAddress.parse(receiverEmail));
            mime.setSubject("Your OTP Code");
            mime.setText("Your OTP code for Verification is: "+otp);
            Transport.send(mime);
            JOptionPane.showMessageDialog(this,"OTP sent !!");
        }catch(MessagingException e){
             JOptionPane.showMessageDialog(this,e);
        }
        
    }
    
    protected String generateOtp(){
        int otp = (int) (Math.random() * 900000) + 100000;
        return String.valueOf(otp);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sender = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        receiver = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        otp = new javax.swing.JTextField();
        send_otp = new javax.swing.JButton();
        verify = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMAIL VERIFICATION PAGE");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("EMAIL VERFICATION PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 23, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("SENDER EMAIL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 125, 110, -1));

        sender.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(sender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 125, 172, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 169, 110, -1));

        password.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 169, 172, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setText("RECEIVER EMAIL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 213, -1, -1));

        receiver.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(receiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 213, 172, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setText("OTP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 260, 49, -1));

        otp.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        getContentPane().add(otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 257, 172, -1));

        send_otp.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        send_otp.setText("SEND OTP");
        send_otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_otpActionPerformed(evt);
            }
        });
        getContentPane().add(send_otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 361, -1, -1));

        verify.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        verify.setText("VERIFY");
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });
        getContentPane().add(verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 361, -1, -1));

        reset.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 361, -1, -1));

        close.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 361, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email_back.jpeg"))); // NOI18N
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new otpEmailVerification().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void send_otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_otpActionPerformed
        // TODO add your handling code here:
        String toEmail = receiver.getText();
        if (toEmail.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Enter a valid email !!");
        }
        else 
        {
            String regex = "^[a-zA-Z0-9]+(?:\\.[a-zA-Z0-9]+)*@(?:[a-z]+\\.)+[a-z]{2,3}";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(toEmail);
            if (matcher.matches()) {
                JOptionPane.showMessageDialog(this, "valid receiver Email");
                generatedOtp = generateOtp();
                sendOtp(toEmail, generatedOtp);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid receiver Email");
            }

        }

    }//GEN-LAST:event_send_otpActionPerformed

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
        // TODO add your handling code here:
        String enteredOtp = otp.getText();
        if (enteredOtp.equals(generatedOtp)) {
            JOptionPane.showMessageDialog(this, "Verification Sucess !!!");
            this.dispose();
             new main_page().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Wrong OTP !! Verification Failed ");
        }

    }//GEN-LAST:event_verifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(otpEmailVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(otpEmailVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(otpEmailVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(otpEmailVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new otpEmailVerification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField otp;
    private javax.swing.JTextField password;
    private javax.swing.JTextField receiver;
    private javax.swing.JButton reset;
    private javax.swing.JButton send_otp;
    private javax.swing.JTextField sender;
    private javax.swing.JButton verify;
    // End of variables declaration//GEN-END:variables
}
